--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: eskimo_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO eskimo_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Categories; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Categories" OWNER TO eskimo_user;

--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrderItems; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."OrderItems" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Name" text NOT NULL,
    "Price" numeric NOT NULL,
    "Quantity" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "ImageUrl" text,
    "Store" text NOT NULL
);


ALTER TABLE public."OrderItems" OWNER TO eskimo_user;

--
-- Name: OrderItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."OrderItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."Orders" (
    "Id" integer NOT NULL,
    "CustomerName" text NOT NULL,
    "DeliveryType" text NOT NULL,
    "Address" text,
    "Street" text,
    "Number" text,
    "Complement" text,
    "Store" text NOT NULL,
    "Total" numeric NOT NULL,
    "Status" text NOT NULL,
    "PhoneNumber" text,
    "DeliveryFee" numeric NOT NULL,
    "ImageUrl" text
);


ALTER TABLE public."Orders" OWNER TO eskimo_user;

--
-- Name: Orders_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Products; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."Products" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Price" numeric NOT NULL,
    "ImageUrl" text,
    "Stock" integer,
    "CategoryId" integer,
    "SubcategoryId" integer
);


ALTER TABLE public."Products" OWNER TO eskimo_user;

--
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."Products" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Settings; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."Settings" (
    "Id" integer NOT NULL,
    "DeliveryRate" numeric NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Settings" OWNER TO eskimo_user;

--
-- Name: Settings_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."Settings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Settings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: StoreProductVisibilities; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."StoreProductVisibilities" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Store" text NOT NULL,
    "IsVisible" boolean NOT NULL
);


ALTER TABLE public."StoreProductVisibilities" OWNER TO eskimo_user;

--
-- Name: StoreProductVisibilities_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."StoreProductVisibilities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StoreProductVisibilities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: StoreStocks; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."StoreStocks" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Store" text NOT NULL,
    "Quantity" integer NOT NULL
);


ALTER TABLE public."StoreStocks" OWNER TO eskimo_user;

--
-- Name: StoreStocks_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."StoreStocks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StoreStocks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Subcategories; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."Subcategories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "CategoryId" integer NOT NULL
);


ALTER TABLE public."Subcategories" OWNER TO eskimo_user;

--
-- Name: Subcategories_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."Subcategories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Subcategories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL
);


ALTER TABLE public."Users" OWNER TO eskimo_user;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: eskimo_user
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: eskimo_user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO eskimo_user;

--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."Categories" ("Id", "Name") FROM stdin;
3	Picolé
4	Pote de Sorvete
5	Tortas
6	Açaí
7	Sundae
8	Extras
9	selleto
10	Complementos
11	Sundae
12	Zero
\.


--
-- Data for Name: OrderItems; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."OrderItems" ("Id", "ProductId", "Name", "Price", "Quantity", "OrderId", "ImageUrl", "Store") FROM stdin;
1	113	+ paçoca	1	1	1	https://eskimo.com.br/wp-content/uploads/2023/04/Pacoca.png	passo
\.


--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."Orders" ("Id", "CustomerName", "DeliveryType", "Address", "Street", "Number", "Complement", "Store", "Total", "Status", "PhoneNumber", "DeliveryFee", "ImageUrl") FROM stdin;
1	crislaine	entregar	Bela Vista	dos bobo 	0	casa	passo	25369.35	pago	5549991259242	25368.35	\N
\.


--
-- Data for Name: Products; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."Products" ("Id", "Name", "Description", "Price", "ImageUrl", "Stock", "CategoryId", "SubcategoryId") FROM stdin;
1	Morango	Fruta Morango PESO LÍQ. 60 g Picolé sabor artificial de morango. Colorido artificialmente. Aromatizado artificialmente.  Alérgicos PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/05/Morango.png.webp	\N	3	1
2	Maracujá	Fruta Maracujá PESO LÍQ. 60 g Picolé sabor artificial de maracujá. Colorido artificialmente. Aromatizado artificialmente.Alérgicos PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/05/Maracuja.png.webp	\N	3	1
3	Crocante	Pote 2 Litros Crocante PESO LÍQ. 950g Sorvete sabor artificial de baunilha e mesclado com amendoim crocante e caramelo. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM AMENDOIM, DERIVADOS DE LEITE. PODE CONTER CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ, AVELÃS, AMÊNDOAS, AVEIA, CEVADA, CENTEIO, SOJA, TRIGO E LÁTEX NATURAL.CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/03/Crocante.png.webp	\N	4	7
4	Maçã Verde + Chantilly	Turma da Mônica Maçã Verde + Chantilly PESO LÍQ. 58 g Picolé sabor maçã verde, recheado com chantilly. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/01/Cebolinha.png.webp	\N	3	1
5	Tutti- Frutti + Chantilly	Turma da Mônica Tutti- Frutti + Chantilly PESO LÍQ. 58 g Picolé sabor artifical de tutti-frutti, recheado com chantilly. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/01/Magali.png.webp	\N	3	1
6	Morango + Chantilly	Turma da Mônica Morango + Chantilly PESO LÍQ. 58 g Picolé de morango, recheado com chantilly. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/01/Monica.png.webp	\N	3	1
7	Frutas Vermelhas	Diamond Frutas Vermelhas PESO LÍQ. 60 g PICOLÉ SABOR FRUTAS VERMELHAS, COBERTO COM CHOCOLATE BRANCO E AMORAS DESIDRATADAS. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AVELÃS, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/01/Diamond-Frutas-vermelhas.png.webp	\N	3	1
8	Pistache	Diamond Pistache PESO LÍQ. 60 g PICOLÉ SABOR ARTIFICIAL DE PISTACHE, COM COBERTURA E COOKIES SABOR PISTACHE. AROMATIZADO ARTIFICIALMENTE. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AMÊNDOA, AVEIA, AVELÃS, CASTANHAS, CASTANHA-DO-PARÁ, CENTEIO, CEVADA, MACADÂMIA, NOZES, OVO, PECÃ, PINOLE, PISTACHE, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2025/01/Diamond-PIstache.png.webp	\N	3	3
9	Patrick	Linha Bob Esponja Patrick PESO LÍQ. 36g PICOLÉ SABOR ARTIFICIAL TUTTI FRUTTI.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2024/07/Patrick.png.webp	\N	3	5
10	Bob Esponja	Linha Bob Esponja Bob Esponja PESO LÍQ. 40g PICOLÉ SABOR BAUNILHA E CHOCOLATE.Alérgicos CONTÉM DERIVADOS AVELÃS, DE LEITE E DE SOJA. PODE CONTER CEVADA, TRIGO, PISTACHE, MACADÂMIA, CASTANHA-DE-CAJU, NOZES, AMÊNDOAS E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2024/07/Bob-Esponja.png.webp	\N	3	5
11	Coco Queimado	Linha + Coco Queimado PESO LÍQ. 50g PICOLÉ SABOR ARTIFICIAL DE COCO QUEIMADO COM PEDAÇOS DE COCO QUEIMADO. AROMATIZADO ARTIFICIALMENTE. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2024/07/Coco-Queimado.png.webp	\N	3	1
12	Tramontaro	Clássicos 1,5 Litros Tramontaro PESO LÍQ. 715 g Sorvete sabor artificial de baunilha e leite condensado, mesclado com creme de avelã, caramelo e castanha-de-caju. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/webp-express/webp-images/uploads/2024/03/Tramontaro-1.png.webp	\N	4	8
13	Banana com Chocotella	Clássicos 1,5 Litros Banana com Chocotella PESO LÍQ. 715 g Sorvete sabor banana, mesclado com chocolate e avelã. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, CASTANHA-DE-CAJU, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/03/Banana-com-Chocotella.png	\N	4	8
14	Letinho Trufado	Clássicos 1,5 Litros Letinho Trufado PESO LÍQ. 715 g Sorvete sabor artificial de leite condensado e leite, mesclado com trufa. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/03/Leitinho-Trufado-1.png	\N	4	8
15	Creme+Flocos+Chocolate	Clássicos 1,5 Litros Creme+Flocos+Chocolate PESO LÍQ. 715 g Sorvete sabor artificial de chocolate, flocos e creme. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/03/CFC.png	\N	4	8
16	Trufa	Clássicos 1,5 Litros Trufa PESO LÍQ. 715 g Sorvete de chocolate, mesclado com recheio de trufa. Aromatizado artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/03/Trufa-1.png	\N	4	8
17	Flocos	Clássicos 1,5 Litros Flocos PESO LÍQ. 715 g Sorvete sabor artificial de nata, mesclado com chocolate meio amargo. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/03/Flocos-1.png	\N	4	8
18	Passas ao Rum	Clássicos 1,5 Litros Passas ao Rum PESO LÍQ. 715 g Sorvete sabor artificial de creme, mesclado com uva passa. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/02/Passas-ao-Rum-2.png	\N	4	8
19	Abacaxi com Coco	Clássicos 1,5 Litros Abacaxi com Coco PESO LÍQ. 715 g Sorvete sabor artificial de leite condensado, mesclado com chocolate e polpa de abacaxi. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/02/Abacaxi-com-Coco-3.png	\N	4	8
20	Marta Rocha	Clássicos 1,5 Litros Marta Rocha PESO LÍQ. 715 g Sorvete sabor artificial de leite condensado, mesclado com chocolate e polpa de abacaxi. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/02/Marta-Rocha-2.png	\N	4	8
21	Chocolak	Clássicos 1,5 Litros Chocolak PESO LÍQ. 715 g Sorvete sabor artificial de chocolate preto e chocolate branco, mesclado com chocolate branco e preto. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/02/Chocolak-2.png	\N	4	8
22	Leite Condensado + Chocolate	Clássicos 1,5 Litros Leite Condensado + Chocolate PESO LÍQ. 715 g Sorvete sabor artificial de leite condensado e chocolate. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/02/Leite-CondensadoChocolate-1.png	\N	4	8
23	Brigadeiro	Clássicos 1,5 Litros Brigadeiro PESO LÍQ. 715 g Sorvete de chocolate, mesclado com granulado. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/02/Brigadeiro-1.png	\N	4	8
24	Nata	Creme Nata PESO LÍQ. 50 g Picolé sabor artificial de nata. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/02/Creme-Nata.png	\N	3	2
25	Choconut	La Sobremesa Choconut PESO LÍQ. 60 g PICOLÉ SABOR CHOCOLATE, RECHEADO COM CHOCOLATE E AVELÃ. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL.Alérgicos CONTÉM AVELÃS, DERIVADOS DO LEITE, DO TRIGO, DA SOJA E DE OVOS. PODE CONTER PISTACHE, MACADÂMIA, CASTANHA-DE-CAJU, NOZES, AMÊNDOAS, AMENDOIM E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/01/Choconut.png	\N	3	11
26	Pudim de Leite	La Sobremesa Pudim de Leite PESO LÍQ. 60 g PICOLÉ SABOR PUDIM DE LEITE, RECHEADO COM CARAMELO. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃS, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/01/Pudim-de-Leite.png	\N	3	11
27	Romeu e Julieta	La Sobremesa Romeu e Julieta PESO LÍQ. 60 g PICOLÉ SABOR CREAM CHEESE, RECHEADO COM GOIABADA. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO, AMENDOIM, AVELÃS, CASTANHA-DE-CAJU E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/01/Romeu-e-Julieta.png	\N	3	11
28	Chocodulce	Best Cup Chocodulce PESO LÍQ. 410 g Sorvete sabor chocolate, Mesclado com doce de leite e biscoito. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM DERIVADOS DE LEITE, DE TRIGO E DE SOJA. PODE CONTER AVELÃS, CASTANHA-DE-CAJU, AMENDOIM, AVEIA, CENTEIO, CEVADA E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/01/BestCup-Chocodulce-1.png	\N	4	9
29	Mil Folhas	Best Cup Mil Folhas PESO LÍQ. 410 g Sorvete sabor artificial macadâmia, Mesclado com leitinho e breadcrumb. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE, DE TRIGO E DE SOJA. PODE CONTER CASTANHA-DE-CAJU, AVELÃS, AMENDOIM, AVEIA, CEVADA, CENTEIO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2024/01/BestCup-Mil-Folhas-1.png	\N	4	9
30	Marta Rocha	Pote 2 Litros Marta Rocha PESO LÍQ. 900 g Sorvete sabor artificial de leite condensado, mesclado com chocolate e polpa de abacaxi. Aromatizado artificialmente. Colorido artificialmente.Alérgicos ALÉRGICOS: CONTÉM DERIVADOS DE LEITE, DE AVELÃS, DE SOJA E DE TRIGO. PODE CONTER AMENDOIM, AVEIA, CENTEIO, CEVADA, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/12/Marta-Rocha.png	\N	4	7
31	Açaí com banana	PESO LÍQ. 900 g Sorbet de açaí com banana. Aromatizado artificialmente. Colorido artificialmente.Alérgicos PODE CONTER LEITE E LÁTEX NATURAL. NÃO CONTÉM GLÚTEN	1	https://eskimo.com.br/wp-content/uploads/2023/12/Acai-Banana-900g-com-lupa_.png	\N	6	12
32	Chococo	Pote 2 Litros Chococo PESO LÍQ. 900 g Sorvete sabor coco, mesclado com trufa. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM CASTANHA-DE-CAJU E DERIVADOS DE LEITE, DE SOJA E DE AVELÃS. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/11/Chococo.png	\N	4	7
33	Baunilha com Chocotella	Sundae Baunilha com Chocotella PESO LÍQ. 80 g SORVETE SABOR BAUNILHA, MESCLADO COM CHOCOLATE E AVELÃ. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos ALÉRGICOS: CONTÉM DERIVADOS DE AVELÃS, DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AMÊNDOAS, CASTANHA-DE-CAJU, PISTACHE, MACADÂMIA, NOZES, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/11/Sundae-Chocotella-1.png	\N	7	14
34	Maracujá	Fruta + calda Maracujá PESO LÍQ. 800 g Sorbet de maracujá. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente. ESTE NÃO É UM ALIMENTO BAIXO OU REDUZIDO EM VALOR ENERGÉTICO.Alérgicos PODE CONTER SOJA, TRIGO, LEITE E LÁTEX NATURAL. CONTÉM GLÚTEN	1	https://eskimo.com.br/wp-content/uploads/2023/11/Maracuja.png	\N	4	8
35	Limão	Fruta + calda Limão PESO LÍQ. 800 g Sorbet de limão. Contém aromatizante. Colorido artificialmente. ESTE NÃO É UM ALIMENTO BAIXO OU REDUZIDO EM VALOR ENERGÉTICO.Alérgicos PODE CONTER SOJA, TRIGO, LEITE E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/11/Limao-2.png	\N	4	8
36	Abacaxi	Fruta + calda Abacaxi PESO LÍQ. 800 g Sorbet de abacaxi. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos PODE CONTER SOJA, TRIGO, LEITE E LÁTEX NATURAL. CONTÉM GLÚTEN	1	https://eskimo.com.br/wp-content/uploads/2023/11/Abacaxi.png	\N	4	8
37	Uva	Fruta + calda Uva PESO LÍQ. 800 g Sorbet de uva. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos PODE CONTER SOJA, TRIGO, LEITE E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/11/Uva.png	\N	4	8
38	Chocolak	Pote 2 Litros Chocolak PESO LÍQ. 900 g Sorvete sabor artificial de chocolate preto e chocolate Branco, mesclado com chocolate branco e preto. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU E DERIVADOS DE LEITE, DE SOJA E DE AVELÃS. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN	1	https://eskimo.com.br/wp-content/uploads/2023/09/Chocolak-1.png	\N	4	7
39	Açaí com guaraná	Açaí com guaraná PESO LÍQ. 230 g Sorbet de açaí com guaraná. Aromatizado artificialmente. Colorido artificialmente.Alérgicos PODE CONTER LÁTEX NATURAL. NÃO CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/07/Acai-com-guarana.png	\N	6	13
40	Açaí com banana	Açaí com banana PESO LÍQ. 230 g Sorbet de açaí com banana. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos PODE CONTER LÁTEX NATURAL. NÃO CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/07/Acai-com-banana.png	\N	6	12
41	Açaí com guaraná	Açaí com guaraná PESO LÍQ. 900 g Sorbet de açaí com guaraná. Aromatizado artificialmente. Colorido artificialmente.Alérgicos PODE CONTER LEITE E LÁTEX NATURAL. NÃO CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/05/Acai-Guarana-900g.png	\N	6	13
42	Abacaxi com coco	Torta de Sorvete Abacaxi com coco PESO LÍQ. 650 g Torta de sorvete sabor de abacaxi com coco. Colorido e aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Torta-de-sorvete-abacaxi-1.png	\N	5	15
43	Iogurte grego com morango	Torta de Sorvete Iogurte grego com morango PESO LÍQ. 650 g Torta de sorvete sabor artificial de iogurte e morango com cobertura de morango. Colorido e aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DERIVADOS DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Torta-de-sorvete-morango-3.png	\N	5	16
44	Fruta do bosco	Sundae Fruta do bosco PESO LÍQ. 80 g Sorvete sabor artificial de nata, mesclado com frutas vermelhas. Colorido e aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Sundae-fruta-do-bosco-1.png	\N	7	14
45	Frutas vermelhas	Sorvete Zero Adição de açúcar Frutas vermelhas PESO LÍQ. 450 g Sorvete sabor artificial de baunilha, mesclado com frutas vermelhas.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Zero-acucar-frutas-vermelhas-3.png	\N	12	17
46	Beijinho	Sorvete Zero Adição de açúcar Beijinho PESO LÍQ. 450 g Sorvete sabor leite de coco e leite condensado, mesclado com coco ralado e damasco.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER DERIVADOS DE SOJA, TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Zero-acucar-beijinho-sirio-4.png	\N	12	17
47	Brigadeiro	Seletto Brigadeiro PESO LÍQ. 85 g Sorvete sabor chocolate, mesclado com granulado e castanha-de-caju. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU E DERIVADOS DA CEVADA, LEITE, AVELÃS E SOJA. PODE CONTER AMENDOIM, MACADÂMIA, NOZES, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Seletto-brigadeiro-sem-lupa.png	\N	9	18
48	Crocante	Seletto Crocante PESO LÍQ. 90 g Sorvete sabor artificial de baunilha coberto com amendoim crocante. Aromatizado artificialmente.Alérgicos ALÉRGICOS: CONTÉM AMENDOIM, DERIVADOS DE LEITE E DE SOJA. PODE CONTER AVELÃ, AMÊNDOA, AVEIA, CENTEIO, CEVADA, CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Seletto-Crocante-sem-lupa.png	\N	9	19
49	Super barrita	Super Barrita Super barrita PESO LÍQ. 72 g Picolé sabor de leite, com recheio de chocolate e cobertura de chocolate branco e amendoim. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM AMENDOIM, DERIVADOS DE LEITE E DE SOJA. PODE CONTER AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Super-barrita-2.png	\N	3	23
50	Coco	Picolé Zero Adição de açúcar Coco PESO LÍQ. 50g Picolé sabor artificial de coco. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.   	1	https://eskimo.com.br/wp-content/uploads/2023/04/Zero-Coco.png	\N	12	20
51	Chocolate	Picolé Zero Adição de açúcar Chocolate PESO LÍQ. 52 g Picolé de chocolateAlérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Creme-Chocolate-3.png	\N	12	21
52	Napolicup	Napolicup Napolicup PESO LÍQ. 120 g Sorvete sabor artificial de creme, chocolate e morango. Aromatizado artificialmente. Colorido artificialmente.Alérgicos ALÉRGICOS: CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Napolicup-1.png	\N	4	22
53	Napolitano	Napolitano Napolitano PESO LÍQ. 55 g Picolé sabor artificial de baunilha, morango e chocolate. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE, DE CEVADA E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Napolitano-4.png	\N	3	24
54	 Maracujá com leite condensado	Los Palitos Mexicanos Maracujá com leite condensado PESO LÍQ. 105 g Picolé sabor maracujá, recheado com leite condensado. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO, AMENDOIM, AVELÃS, CASTANHA-DE-CAJU E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Maracuja-com-leite-condensado.png	\N	3	25
55	Chocolate com brigadeiro	Los Palitos Mexicanos Chocolate com brigadeiro PESO LÍQ. 104 picolé sabor artificial de chocolate, com recheio de brigadeiro colorido artificialmente. aromatizado artificialmenteAlérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Chocolate-com-brigadeiro.png	\N	3	25
56	Leitinho trufado	Los Palitos Mexicanos Leitinho trufado PESO LÍQ. 105 g PICOLÉ SABOR LEITE, RECHEADO COM CHOCOLATE TRUFADO MEIO AMARGO. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTEAlérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, AMÊNDOA, NOZES, MACADÂMIA, PISTACHE, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Leitinho-trufado-4.png	\N	3	25
57	Morango com leite condensado	Los Palitos Mexicanos Morango com leite condensado PESO LÍQ. 104 g PICOLÉ DE MORANGO, RECHEADO COM LEITE CONDENSADO. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTEAlérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Morango-com-leite-condensado.png	\N	3	25
58	Torta de Limão	La Sobremesa Torta de Limão PESO LÍQ. 75 g PICOLÉ SABOR TORTA DE LIMÃO, COBERTO COM CHOCOLATE BRANCO E BISCOITO. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM AMENDOIM, DERIVADOS DE LEITE, DE TRIGO, SOJA. PODE CONTER AVEIA, CEVADA, CENTEIO, AVELÃ, NOZES, MACADÂMIA, CASTANHA-DE-CAJU, CASTANHA-DO-PARA E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Torta-de-Limao-1.png	\N	3	25
59	Torta de Amendoim	La Sobremesa Torta de Amendoim PESO LÍQ. 75 g PICOLÉ SABOR ARTIFICIAL DE TORTA DE AMENDOIM, RECHEADO COM CARAMELO E AMENDOIM, COBERTO COM CHOCOLATE MEIO AMARGO. COLORIDO ARTIFICIALMENTE. AROMATIZADO ARTIFICIALMENTE.Alérgicos CONTÉM AMENDOIM E DERIVADOS. CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Torta-de-Amendoim.png	\N	3	25
60	Sagu	 La Sobremesa Sagu PESO LÍQ. 65 g PICOLÉ SABOR SAGU DE UVA, RECHEADO COM CREME BRANCO. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Sagu.png	\N	3	11
61	Quatro leites com amarena	La Sobremesa Quatro leites com amarena PESO LÍQ. 75 g PICOLÉ SABOR NATA, LEITE DE COCO, LEITE CONDENSADO, RECHEADO COM AMARENA E COBERTO COM CHOCOLATE BRANCO. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTEAlérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AVELÃ, CASTANHA-DE-CAJU, AMENDOIM, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Quatro-leites-com-amarena.png	\N	3	11
62	Chocolate com Coco	La Sobremesa Chocolate com Coco PESO LÍQ. 60 g PICOLÉ SABOR ARTIFICIAL DE TRUFA, RECHEADO COM LEITINHO, CREME DE LEITE E COCO. AROMATIZADO ARTIFICIALMENTE.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE SOJA, DE AVELÃ E DE LEITE. PODE CONTER AMENDOIM, AMÊNDOA, NOZES, MACADÂMIA, PISTACHE, CASTANHA-DO-PARÁ E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Chocolate-com-Coco.png	\N	3	11
63	Baunilha com Chocotella	La Sobremesa Baunilha com Chocotella PESO LÍQ. 75 g PICOLÉ SABOR BAUNILHA COM CARAMELO, RECHEADO COM AVELÃ, CREME DE LEITE E COBERTO COM CHOCOLATE BRANCO. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE, DE AVELÃ E DE SOJA. PODE CONTER AMENDOIM, AMÊNDOA, NOZES, MACADÂMIA, TRIGO, PISTACHE, CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Baunilha-com-Chocotella.png	\N	3	11
64	Chicletes	Ituzinho Chicletes PESO LÍQ. 70 g Picolé sabor artificial de chicletes com recheio artificial de tutti-frutti. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Chiclete.png	\N	3	4
65	Leitinho trufado	Ituzinho Leitinho trufado PESO LÍQ. 70 g Picolé sabor leite recheado com chocolate trufado contém aromatizante sintético idêntico ao natural. Colorido artificialmenteAlérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, AMÊNDOA, NOZES, MACADÂMIA, PISTACHE, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Leitinho-trufado-3.png	\N	3	4
66	Banana flambada	Ituzinho Banana flambada PESO LÍQ. 70 g Picolé sabor banana, com recheio de banana caramelizada. Contém aromatizante sintético idêntico ao natural. Colorido artificialmenteAlérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN. 	1	https://eskimo.com.br/wp-content/uploads/2023/04/Banana-flambada.png	\N	3	4
67	Mousse de maracujá	tuzinho Mousse de maracujá PESO LÍQ. 70 g PICOLÉ SABOR MARACUJÁ RECHEADO COM POLPA DE MARACUJÁ. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Maracuja.png	\N	3	4
68	Picolápis Supresa	Kids Picolápis Supresa PESO LÍQ. 30 g Picolé sabor artificial de chicletes colorido artificialmente. Aromatizado artificialmente.Alérgicos PODE CONTER LEITE, TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Picolapis-supresa.png	\N	3	5
69	Molequinho	Kids Molequinho PESO LÍQ. 53 g Picolé sabor artificial amendoim, coberto com chocolate meio amargo e Castanha-de-caju. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AMENDOIM, DE CENTEIO E DE SOJA. PODE CONTER AVEIA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Molequinho.png	\N	3	5
70	Estrela	Kids Estrela PESO LÍQ. 45 g Picolé sabor iogurte com morango coberto com chocolate branco. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Estrela.png	\N	3	5
71	Unicórnio	Kids Unicórnio PESO LÍQ. 56 g Picolé sabor artificial de algodão doce. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN. 	1	https://eskimo.com.br/wp-content/uploads/2023/04/Unicornio-1.png	\N	3	5
72	Mini saia	Fruta Mini saia PESO LÍQ. 58 g Picolé sabor artificial de abacaxi e morango. Colorido artificialmente. Aromatizado artificialmente.Alérgicos PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Mini-saia1.png	\N	3	1
73	Framboesa	Fruta Framboesa PESO LÍQ. 58 g Picolé sabor artificial de framboesa. Colorido artificialmente. Aromatizado artificialmente.Alérgicos PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Framboesa1.png	\N	3	1
74	Abacaxi	Fruta Abacaxi PESO LÍQ. 58 g Picolé de abacaxi. Colorido artificialmente. Aromatizado artificialmente.Alérgicos PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Abacaxi1.png	\N	3	1
75	Uva	Fruta Uva PESO LÍQ. 58 g Picolé de uva. Colorido artificialmente. Aromatizado artificialmente.Alérgicos PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Uva1.png	\N	3	1
76	Frutas vermelhas	Grego Frutas vermelhas PESO LÍQ. 45 g Picolé sabor artificial de iogurte, mesclado com calda de frutas vermelhas. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Frutas-vermelhas.png	\N	3	6
77	Nata trufada	Grand Nevado Nata trufada PESO LÍQ. 715 g Sorvete sabor artificial de nata, mesclado com trufa. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN	1	https://eskimo.com.br/wp-content/uploads/2023/04/Nevado-Nata-Trufada-4.png	\N	4	10
78	Iogurte grego com amora	Grand Nevado Iogurte grego com amora PESO LÍQ. 715 g Sorvete sabor artificial de iogurte, mesclado com polpa de amora. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Nevado-Grego-com-amora-4.png	\N	4	10
79	Trufa	Pote 2 Litros Trufa PESO LÍQ. 900 g Sorvete de chocolate, mesclado com recheio de trufa. Aromatizado artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE E DE AVELÃS. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Trufa.png	\N	4	7
80	Tramontaro	Pote 2 Litros Tramontaro PESO LÍQ. 900 g SORVETE SABOR ARTIFICIAL DE BAUNILHA E LEITE CONDENSADO, MESCLADO COM CREME DE AVELÃ, CARAMELO E CASTANHA-DE-CAJU. AROMATIZADO ARTIFICIALMENTE. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Tramontaro.png	\N	4	7
81	Passas ao rum	Pote 2 Litros Passas ao rum PESO LÍQ. 900 g Sorvete sabor artificial de creme, mesclado com uva passa. Aromatizado artificialmente. Colorido artificialmenteAlérgicos ALÉRGICOS: CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Passas-ao-rum.png	\N	4	7
82	Nata + uva	Pote 2 Litros Nata + uva PESO LÍQ. 900 g Sorvete sabor artificial de uva e nata. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Nata-uva.png	\N	4	7
83	Napolitano	Pote 2 Litros Napolitano PESO LÍQ. 900 g SORVETE SABOR ARTIFICIAL DE CREME, CHOCOLATE E MORANGO. AROMATIZADO ARTIFICIALMENTE. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Napolitano.png	\N	4	7
84	Flocos + morango	Pote 2 Litros Flocos + morango PESO LÍQ. 900 g SORVETE SABOR ARTIFICIAL DE FLOCOS E MORANGO. AROMATIZADO ARTIFICIALMENTE. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Morango-e-flocos.png	\N	4	7
85	Leitinho trufado	Pote 2 Litros Leitinho trufado PESO LÍQ. 900 g Sorvete sabor artificial de leite condensado e leite, mesclado com trufa. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE E DE AVELÃS. PODE CONTER SOJA,AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, CASTANHA-DO-PARÁ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Leitinho-trufado.png	\N	4	7
86	Leite condensado + chocolate	Pote 2 Litros Leite condensado + chocolate PESO LÍQ. 900 g Sorvete sabor artificial de leite condensado e chocolate. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Leite-condensado-chocolate.png	\N	4	7
87	Flocos	Pote 2 Litros Flocos PESO LÍQ. 900 g SORVETE SABOR ARTIFICIAL DE NATA, MESCLADO COM CHOCOLATE MEIO AMARGO. AROMATIZADO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Flocos.png	\N	4	7
88	Creme	Pote 2 Litros Creme PESO LÍQ. 900 g Sorvete sabor artificial de creme. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Creme.png	\N	4	7
89	Creme + flocos + chocolate	Pote 2 Litros Creme + flocos + chocolate PESO LÍQ. 900 g SORVETE SABOR ARTIFICIAL DE CHOCOLATE, FLOCOS E CREME. AROMATIZADO ARTIFICIALMENTE. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AVELÃS, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Creme-floco-e-chocolate.png	\N	4	7
90	Coco + milho verde	Pote 2 Litros Coco + milho verde PESO LÍQ. 900 g Sorvete sabor artificial de coco e milho verde. Aromatizado artificialmente. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, CASTANHA-DE-CAJU, AVELÃ, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/09/Coco-e-milho-verde.png	\N	4	7
112	Skimo	Bombom no Palito Skimo PESO LÍQ. 62 g Picolé sabor artificial de nata, coberto com chocolate meio amargo. Colorido artificialmente. Aromatizado artificialmente.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Skimo.png	\N	3	28
91	Chocomenta	Pote 2 Litros Chocomenta PESO LÍQ. 900 g Sorvete sabor chocolate e menta. Contêm aromatizante sintético idêntico ao natural. Colorido Artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Chocomenta.png	\N	4	7
93	Brigadeiro	Pote 2 Litros Brigadeiro PESO LÍQ. 900 g Sorvete de chocolate, mesclado com granulado. Colorido e aromatizado artificialmente.Alérgicos CONTÉM CASTANHA-DE-CAJU E DERIVADOS DE LEITE, DE SOJA E DE AVELÃS. PODE CONTER AMENDOIM, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Brigadeiro.png	\N	4	7
92	Chocolate branco	Pote 2 Litros Chocolate branco PESO LÍQ. 900 g Sorvete sabor chocolate branco. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Chocolate-branco.png	\N	4	7
94	Banana com chocotella	Pote 2 Litros Banana com chocotella PESO LÍQ. 900 g SORVETE SABOR BANANA, MESCLADO COM CHOCOLATE E AVELÃ. CONTÉM AROMATIZANTE SINTÉTICO IDÊNTICO AO NATURAL. COLORIDO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE, DE AVELÃS E DE SOJA. PODE CONTER AMENDOIM, CASTANHA-DE-CAJU, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Banana-com-chocotella.png	\N	4	7
95	Abacaxi com coco	Pote 2 Litros Abacaxi com coco PESO LÍQ. 900 g Sorvete sabor artificial de abacaxi e coco. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Abacaxi-com-coco.png	\N	4	7
96	Morango	Pote 2 Litros Morango PESO LÍQ. 900 g Sorvete sabor morango, mesclado com cobertura de morango. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/08/Morango.png	\N	4	7
97	Chocomalt	Diamond Chocomalt PESO LÍQ. 64 g Picolé sabor chocolate maltado, coberto com chocolate meio amargo. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM DERIVADOS DE LEITE, DE SOJA E DE CEVADA. PODE CONTER AVEIA, CENTEIO, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Diamond-Chocomalt.png	\N	3	3
98	Cookies Bianco	Diamond Cookies Bianco PESO LÍQ. 60 g Picolé sabor artificial de biscoito e chocolate branco, coberto com chocolate branco e cookies. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DA CEVADA, DE TRIGO, DO LEITE E DA SOJA. PODE CONTER AVEIA, AMENDOIM, AVELÃS, NOZES, CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ, CENTEIO, MACADÂMIA E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN. 	1	https://eskimo.com.br/wp-content/uploads/2023/04/Diamond-Cookies-bianco.png	\N	3	3
99	Cookies	Diamond Cookies PESO LÍQ. 60 g Picolé sabor baunilha e chocolate, coberto com chocolate meio amargo e cookies. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE AVELÃS, DE CEVADA, DE LEITE, DE TRIGO E DE SOJA. PODE CONTER AMENDOIM, CENTEIO, NOZES, MACADÂMIA, PISTACHE, AMÊNDOA, AVEIA, CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Diamond-Cookies-3.png	\N	3	3
100	Limão	Fruta Limão PESO LÍQ. 58 g PICOLÉ SABOR LIMÃO. CONTÉM AROMATIZANTE.Alérgicos PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Limao1.png	\N	3	1
101	Morango	Creme Morango PESO LÍQ. 50 g Picolé sabor morango. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Creme-Morango.png	\N	3	2
102	Milho verde	Creme Milho verde PESO LÍQ. 52 g Picolé sabor artificial de milho verde. Colorido artificialmente. Aromatizado artificialmente. Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Creme-Milho-verde.png	\N	3	2
103	Leite Condensado	Creme Leite Condensado PESO LÍQ. 50 g Picolé sabor artificial de leite condensado. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Creme-Leite-condensado.png	\N	3	2
104	Coco	Creme Coco PESO LÍQ. 52 g Picolé de coco branco. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Creme-Coco.png	\N	3	2
105	Chocolate	Creme Chocolate PESO LÍQ. 58 g Picolé sabor chocolate. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE. PODE CONTER SOJA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Creme-Chocolate.png	\N	3	2
106	Chocolate	Creme Speciale Chocolate PESO LÍQ. 45 g Picolé sabor chocolate Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE CEVADA, DE AVELÃS, DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AMÊNDOA, CASTANHA-DO-PARÁ, CASTANHA-DE-CAJU, MACADÂMIA, NOZES, PISTACHE E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Speciale-Chocolate.png	\N	3	2
107	Torta de limão	Copinho Gourmet Torta de limão PESO LÍQ. 75 g Sorvete sabor torta de limão com cookies. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM AMENDOIM, DERIVADOS DE LEITE, DE SOJA, DE AVEIA, DE CEVADA, DE CENTEIO E DE TRIGO. PODE CONTER AVELÃ, NOZES, MACADÂMIA, CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ, OVOS E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Torta-de-Limao-2.png	\N	4	27
108	Caramelo Salgado	 Copinho Gourmet Caramelo Salgado PESO LÍQ. 75 g Sorvete de caramelo mesclado com cookies de chocolate. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM DERIVADOS DE LEITE, DERIVADOS DE SOJA, TRIGO, AVELÃ. PODE CONTER OVOS, CENTEIO, CEVADA, AVEIA E LÁTEX NATURAL. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Caramelo-Salgado.png	\N	4	27
109	Morango ao leite	Copinho Gourmet Morango ao leite PESO LÍQ. 80 g Sorvete sabor morango, mesclado com leitinho. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AVELÃ, AMENDOIM, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Morango-ao-leite-2.png	\N	4	27
110	Bombom de coco	Copinho Gourmet Bombom de coco PESO LÍQ. 75 g Sorvete de coco, mesclado com chocolate branco. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Bombom-de-coco-2.png	\N	4	27
111	Brigadeiro	Bombom no Palito Brigadeiro PESO LÍQ. 62 g Picolé sabor chocolate, coberto com chocolate meio amargo e granulado. Contém aromatizante sintético idêntico ao natural. Colorido artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE, DE CEVADA E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Brigadeiro.png	\N	3	28
114	+ coco	Linha + + coco PESO LÍQ. 58 g Picolé de coco com pedaços de coco. Contém aromatizante sintético idêntico ao natural.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Coco.png	\N	3	29
113	+ paçoca	Linha + + paçoca PESO LÍQ. 60 g Picolé sabor amendoim.Alérgicos CONTÉM DERIVADOS DE LEITE E AMENDOIM. PODE CONTER DERIVADOS DE SOJA, TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Pacoca.png	\N	3	29
115	Pão de mel	Pão de mel PESO LÍQ. 410 g Sorvete sabor artificial de pão de mel, mesclado Com doce de leite e brownie. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA, TRIGO. PODE CONTER AVELÃ, AVEIA, CENTEIO, CEVADA, NOZES, MACADÂMIA, CASTANHA-DO-PARÁ, CASTANHA-DE-CAJU E LÁTEX NATURAL. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/BestCup-Pao-de-mel.png	\N	4	9
116	Mocaffé	Best Cup Mocaffé PESO LÍQ. 410 g SORVETE SABOR ARTIFICIAL DE CAFÉ, MESCLADO COM CARAMELO. COLORIDO ARTIFICIALMENTE. AROMATIZADO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AVELÃ, CASTANHA-DE-CAJU, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/09/BestCup-mocaffe-2.png	\N	4	9
117	Floresta Negra	Best Cup Floresta Negra PESO LÍQ. 410 g SORVETE DE CHOCOLATE, MESCLADO COM CALDA DE CEREJA. COLORIDO ARTIFICIALMENTE. AROMATIZADO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER AMENDOIM, AMÊNDOAS, AVELÃS, CASTANHA-DE-CAJU, CASTANHA-DO-PARÁ, NOZES, PISTACHE, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/09/BestCup-Floresta-negra-1.png	\N	4	9
118	Doce de leite	Best Cup Doce de leite PESO LÍQ. 410 g SORVETE SABOR ARTIFICIAL DE DOCE DE LEITE, MESCLADO COM DOCE DE LEITE. COLORIDO ARTIFICIALMENTE. AROMATIZADO ARTIFICIALMENTE.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/BestCup-Doce-de-leite-2.png	\N	4	9
119	Chocomalt	Best Cup Chocomalt PESO LÍQ. 410 g Sorvete sabor chocolate com malte, mesclado com flocos crocante. Colorido e aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE, DE TRIGO, DE CEVADA, DE OVOS E DE SOJA. PODE CONTER AMENDOIM, AVELÃS, CASTANHA-DE-CAJU E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/09/BestCup-Chocomalt-2.png	\N	4	9
120	Chocotella	Best Cup Chocotella PESO LÍQ. 410 g Sorvete de chocolate com avelã, Com pedaços de avelã e biscoito. Colorido artificialmente. Aromatizado artificialmente.Alérgicos ONTÉM AVELÃS E DERIVADOS. CONTÉM DERIVADOS DE LEITE, DE SOJA, DE TRIGO E DE OVOS. PODE CONTER AMENDOIM, AMÊNDOAS, NOZES, MACADÂMIAS, PISTACHES, CASTANHA-DE-CAJU E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/BestCup-Chocotella.png	\N	4	9
121	Coco	Best Cup Coco PESO LÍQ. 410 g Sorvete sabor artificial de coco, mesclado com coco. Colorido e aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE, DERIVADOS DE SOJA, CASTANHA-DE-CAJU. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/BestCup-Bombom-de-coco.png	\N	4	9
122	Abacaxi ao vinho	Best Cup Abacaxi ao vinho PESO LÍQ. 410 g Sorvete sabor artificial de abacaxi ao vinho. Colorido artificialmente. Aromatizado artificialmente.Alérgicos CONTÉM DERIVADOS DE LEITE E DE SOJA. PODE CONTER TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/09/BestCup-Abacaxi-ao-vinho-1.png	\N	4	9
123	Pistache	Best Cup Pistache PESO LÍQ. 410 g SORVETE SABOR ARTIFICIAL DE PISTACHE, MESCLADO COM CASTANHA-DE-CAJU. COLORIDO ARTIFICIALMENTE. AROMATIZADO ARTIFICIALMENTE.Alérgicos CONTÉM CASTANHA-DE-CAJU E DERIVADOS DE LEITE, DE SOJA E DE CEVADA. PODE CONTER CENTEIO, AVEIA, TRIGO E LÁTEX NATURAL. CONTÉM LACTOSE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/09/BestCup-Pistache-1.png	\N	4	9
124	Cascão	Cascão colorido e aromatizado artificialmente. Conservar em local seco, fresco e inodoro.Alérgicos CONTÉM DERIVADOS DE TRIGO E DE SOJA. PODE CONTER LEITE. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Cascao-1.png	\N	8	30
127	Coberturas Caramelo	Coberturas Caramelo PESO LÍQ. 270 g Cobertura sabor caramelo colorida artificialmente	1	https://eskimo.com.br/wp-content/uploads/2023/04/Cobertura-Caramelo.png	\N	8	34
128	Farofa Doce	Farofa Doce PESO LÍQ. 100 g farofa doce crocante de castanha-de-cajuAlérgicos CONTÉM CASTANHA-DE-CAJU, DERIVADOS DE LEITE E DE CEVADA. PODE CONTER AMENDOIM, AVEIA, AVELÃ, CENTEIO, NOZES, SOJA E TRIGO. CONTÉM GLÚTEN. CONTÉM LACTOSE.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Farofa-Doce-1.png	\N	8	33
125	Coberturas de Chocolate	Coberturas Chocolate PESO LÍQ. 270 g Cobertura sabor chocolateAlérgicos PODE CONTER AMENDOIM, AVEIA, AVELÃ, CASTANHA-DECAJU, CENTEIO, CEVADA, LEITE, NOZES, SOJA E TRIGO. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Cobertura-Chocolate.png	\N	8	31
126	Coberturas de Morango	Coberturas Morango PESO LÍQ. 270 g Cobertura sabor artificial de morango colorida artificialmenteAlérgicos PODE CONTER AMENDOIM, AVEIA, AVELÃ, CASTANHA-DECAJU, CENTEIO, CEVADA, LEITE, NOZES, SOJA E TRIGO. CONTÉM GLÚTEN.	1	https://eskimo.com.br/wp-content/uploads/2023/04/Cobertura-morango.png	\N	8	32
\.


--
-- Data for Name: Settings; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."Settings" ("Id", "DeliveryRate", "CreatedAt", "UpdatedAt") FROM stdin;
1	2.5	2025-07-30 17:15:43.192489	2025-07-30 17:15:43.19252
\.


--
-- Data for Name: StoreProductVisibilities; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."StoreProductVisibilities" ("Id", "ProductId", "Store", "IsVisible") FROM stdin;
1	1	efapi	f
2	1	palmital	f
3	1	passo	f
4	2	efapi	f
5	2	palmital	f
6	2	passo	f
7	3	efapi	f
8	3	palmital	f
9	3	passo	f
10	4	efapi	f
11	4	palmital	f
12	4	passo	f
13	5	efapi	f
14	5	palmital	f
15	5	passo	f
16	6	efapi	f
17	6	palmital	f
18	6	passo	f
19	7	efapi	f
20	7	palmital	f
21	7	passo	f
22	8	efapi	f
23	8	palmital	f
24	8	passo	f
25	9	efapi	f
26	9	palmital	f
27	9	passo	f
28	10	efapi	f
29	10	palmital	f
30	10	passo	f
31	11	efapi	f
32	11	palmital	f
33	11	passo	f
34	12	efapi	f
35	12	palmital	f
36	12	passo	f
37	13	efapi	f
38	13	palmital	f
39	13	passo	f
40	14	efapi	f
41	14	palmital	f
42	14	passo	f
43	15	efapi	f
44	15	palmital	f
45	15	passo	f
46	16	efapi	f
47	16	palmital	f
48	16	passo	f
49	17	efapi	f
50	17	palmital	f
51	17	passo	f
52	18	efapi	f
53	18	palmital	f
54	18	passo	f
55	19	efapi	f
56	19	palmital	f
57	19	passo	f
58	20	efapi	f
59	20	palmital	f
60	20	passo	f
61	21	efapi	f
62	21	palmital	f
63	21	passo	f
64	22	efapi	f
65	22	palmital	f
66	22	passo	f
67	23	efapi	f
68	23	palmital	f
69	23	passo	f
70	24	efapi	f
71	24	palmital	f
72	24	passo	f
73	25	efapi	f
74	25	palmital	f
75	25	passo	f
76	26	efapi	f
77	26	palmital	f
78	26	passo	f
79	27	efapi	f
80	27	palmital	f
81	27	passo	f
82	28	efapi	f
83	28	palmital	f
84	28	passo	f
85	29	efapi	f
86	29	palmital	f
87	29	passo	f
88	30	efapi	f
89	30	palmital	f
90	30	passo	f
91	31	efapi	f
92	31	palmital	f
93	31	passo	f
94	32	efapi	f
95	32	palmital	f
96	32	passo	f
97	33	efapi	f
98	33	palmital	f
99	33	passo	f
100	34	efapi	f
101	34	palmital	f
102	34	passo	f
103	35	efapi	f
104	35	palmital	f
105	35	passo	f
106	36	efapi	f
107	36	palmital	f
108	36	passo	f
109	37	efapi	f
110	37	palmital	f
111	37	passo	f
112	38	efapi	f
113	38	palmital	f
114	38	passo	f
115	39	efapi	f
116	39	palmital	f
117	39	passo	f
118	40	efapi	f
119	40	palmital	f
120	40	passo	f
121	41	efapi	f
122	41	palmital	f
123	41	passo	f
124	42	efapi	f
125	42	palmital	f
126	42	passo	f
127	43	efapi	f
128	43	palmital	f
129	43	passo	f
130	44	efapi	f
131	44	palmital	f
132	44	passo	f
133	45	efapi	f
134	45	palmital	f
135	45	passo	f
136	46	efapi	f
137	46	palmital	f
138	46	passo	f
139	47	efapi	f
140	47	palmital	f
141	47	passo	f
142	48	efapi	f
143	48	palmital	f
144	48	passo	f
145	49	efapi	f
146	49	palmital	f
147	49	passo	f
148	50	efapi	f
149	50	palmital	f
150	50	passo	f
151	51	efapi	f
152	51	palmital	f
153	51	passo	f
154	52	efapi	f
155	52	palmital	f
156	52	passo	f
157	53	efapi	f
158	53	palmital	f
159	53	passo	f
160	54	efapi	f
161	54	palmital	f
162	54	passo	f
163	55	efapi	f
164	55	palmital	f
165	55	passo	f
166	56	efapi	f
167	56	palmital	f
168	56	passo	f
169	57	efapi	f
170	57	palmital	f
171	57	passo	f
172	58	efapi	f
173	58	palmital	f
174	58	passo	f
175	59	efapi	f
176	59	palmital	f
177	59	passo	f
178	60	efapi	f
179	60	palmital	f
180	60	passo	f
181	61	efapi	f
182	61	palmital	f
183	61	passo	f
184	62	efapi	f
185	62	palmital	f
186	62	passo	f
187	63	efapi	f
188	63	palmital	f
189	63	passo	f
190	64	efapi	f
191	64	palmital	f
192	64	passo	f
193	65	efapi	f
194	65	palmital	f
195	65	passo	f
196	66	efapi	f
197	66	palmital	f
198	66	passo	f
199	67	efapi	f
200	67	palmital	f
201	67	passo	f
202	68	efapi	f
203	68	palmital	f
204	68	passo	f
205	69	efapi	f
206	69	palmital	f
207	69	passo	f
208	70	efapi	f
209	70	palmital	f
210	70	passo	f
211	71	efapi	f
212	71	palmital	f
213	71	passo	f
214	72	efapi	f
215	72	palmital	f
216	72	passo	f
217	73	efapi	f
218	73	palmital	f
219	73	passo	f
220	74	efapi	f
221	74	palmital	f
222	74	passo	f
223	75	efapi	f
224	75	palmital	f
225	75	passo	f
226	76	efapi	f
227	76	palmital	f
228	76	passo	f
229	77	efapi	f
230	77	palmital	f
231	77	passo	f
232	78	efapi	f
233	78	palmital	f
234	78	passo	f
235	79	efapi	f
236	79	palmital	f
237	79	passo	f
238	80	efapi	f
239	80	palmital	f
240	80	passo	f
241	81	efapi	f
242	81	palmital	f
243	81	passo	f
244	82	efapi	f
245	82	palmital	f
246	82	passo	f
247	83	efapi	f
248	83	palmital	f
249	83	passo	f
250	84	efapi	f
251	84	palmital	f
252	84	passo	f
253	85	efapi	f
254	85	palmital	f
255	85	passo	f
256	86	efapi	f
257	86	palmital	f
258	86	passo	f
259	87	efapi	f
260	87	palmital	f
261	87	passo	f
262	88	efapi	f
263	88	palmital	f
264	88	passo	f
265	89	efapi	f
266	89	palmital	f
267	89	passo	f
268	90	efapi	f
269	90	palmital	f
270	90	passo	f
271	91	efapi	f
272	91	palmital	f
273	91	passo	f
274	92	efapi	f
275	92	palmital	f
276	92	passo	f
277	93	efapi	f
278	93	palmital	f
279	93	passo	f
280	94	efapi	f
281	94	palmital	f
282	94	passo	f
283	95	efapi	f
284	95	palmital	f
285	95	passo	f
286	96	efapi	f
287	96	palmital	f
288	96	passo	f
289	97	efapi	f
290	97	palmital	f
291	97	passo	f
292	98	efapi	f
293	98	palmital	f
294	98	passo	f
295	99	efapi	f
296	99	palmital	f
297	99	passo	f
298	100	efapi	f
299	100	palmital	f
300	100	passo	f
301	101	efapi	f
302	101	palmital	f
303	101	passo	f
304	102	efapi	f
305	102	palmital	f
306	102	passo	f
307	103	efapi	f
308	103	palmital	f
309	103	passo	f
310	104	efapi	f
311	104	palmital	f
312	104	passo	f
313	105	efapi	f
314	105	palmital	f
315	105	passo	f
316	106	efapi	f
317	106	palmital	f
318	106	passo	f
319	107	efapi	f
320	107	palmital	f
321	107	passo	f
322	108	efapi	f
323	108	palmital	f
324	108	passo	f
325	109	efapi	f
326	109	palmital	f
327	109	passo	f
328	110	efapi	f
329	110	palmital	f
330	110	passo	f
331	111	efapi	f
332	111	palmital	f
333	111	passo	f
334	112	efapi	f
335	112	palmital	f
336	112	passo	f
337	113	efapi	f
338	113	palmital	f
339	113	passo	f
340	114	efapi	f
341	114	palmital	f
342	114	passo	f
343	115	efapi	f
344	115	palmital	f
345	115	passo	f
346	116	efapi	f
347	116	palmital	f
348	116	passo	f
349	117	efapi	f
350	117	palmital	f
351	117	passo	f
352	118	efapi	f
353	118	palmital	f
354	118	passo	f
355	119	efapi	f
356	119	palmital	f
357	119	passo	f
358	120	efapi	f
359	120	palmital	f
360	120	passo	f
361	121	efapi	f
362	121	palmital	f
363	121	passo	f
364	122	efapi	f
365	122	palmital	f
366	122	passo	f
367	123	efapi	f
368	123	palmital	f
369	123	passo	f
370	124	efapi	f
371	124	palmital	f
372	124	passo	f
373	125	efapi	f
374	125	palmital	f
375	125	passo	f
376	126	efapi	f
377	126	palmital	f
378	126	passo	f
379	127	efapi	f
380	127	palmital	f
381	127	passo	f
382	128	efapi	f
383	128	palmital	f
384	128	passo	f
\.


--
-- Data for Name: StoreStocks; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."StoreStocks" ("Id", "ProductId", "Store", "Quantity") FROM stdin;
1	1	efapi	1
2	1	palmital	1
3	1	passo	1
4	2	efapi	1
5	2	palmital	1
6	2	passo	1
7	3	efapi	1
8	3	palmital	1
9	3	passo	1
10	4	efapi	1
11	4	palmital	1
12	4	passo	1
13	5	efapi	1
14	5	palmital	1
15	5	passo	1
16	6	efapi	1
17	6	palmital	1
18	6	passo	1
19	7	efapi	1
20	7	palmital	1
21	7	passo	1
22	8	efapi	1
23	8	palmital	1
24	8	passo	1
25	9	efapi	1
26	9	palmital	1
27	9	passo	1
28	10	efapi	1
29	10	palmital	1
30	10	passo	1
31	11	efapi	1
32	11	palmital	1
33	11	passo	1
34	12	efapi	1
35	12	palmital	1
36	12	passo	1
37	13	efapi	1
38	13	palmital	1
39	13	passo	1
40	14	efapi	1
41	14	palmital	1
42	14	passo	1
43	15	efapi	1
44	15	palmital	1
45	15	passo	1
46	16	efapi	1
47	16	palmital	1
48	16	passo	1
49	17	efapi	1
50	17	palmital	1
51	17	passo	1
52	18	efapi	1
53	18	palmital	1
54	18	passo	1
55	19	efapi	1
56	19	palmital	1
57	19	passo	1
58	20	efapi	1
59	20	palmital	1
60	20	passo	1
61	21	efapi	1
62	21	palmital	1
63	21	passo	1
64	22	efapi	1
65	22	palmital	1
66	22	passo	1
67	23	efapi	1
68	23	palmital	1
69	23	passo	1
70	24	efapi	1
71	24	palmital	1
72	24	passo	1
73	25	efapi	1
74	25	palmital	1
75	25	passo	1
76	26	efapi	1
77	26	palmital	1
78	26	passo	1
79	27	efapi	1
80	27	palmital	1
81	27	passo	1
82	28	efapi	1
83	28	palmital	1
84	28	passo	1
85	29	efapi	1
86	29	palmital	1
87	29	passo	1
88	30	efapi	1
89	30	palmital	1
90	30	passo	1
91	31	efapi	1
92	31	palmital	1
93	31	passo	1
94	32	efapi	1
95	32	palmital	1
96	32	passo	1
97	33	efapi	1
98	33	palmital	1
99	33	passo	1
100	34	efapi	1
101	34	palmital	1
102	34	passo	1
103	35	efapi	1
104	35	palmital	1
105	35	passo	1
106	36	efapi	1
107	36	palmital	1
108	36	passo	1
109	37	efapi	1
110	37	palmital	1
111	37	passo	1
112	38	efapi	1
113	38	palmital	1
114	38	passo	1
115	39	efapi	1
116	39	palmital	1
117	39	passo	1
118	40	efapi	1
119	40	palmital	1
120	40	passo	1
121	41	efapi	1
122	41	palmital	1
123	41	passo	1
124	42	efapi	1
125	42	palmital	1
126	42	passo	1
127	43	efapi	1
128	43	palmital	1
129	43	passo	1
130	44	efapi	1
131	44	palmital	1
132	44	passo	1
133	45	efapi	1
134	45	palmital	1
135	45	passo	1
136	46	efapi	1
137	46	palmital	1
138	46	passo	1
139	47	efapi	1
140	47	palmital	1
141	47	passo	1
142	48	efapi	1
143	48	palmital	1
144	48	passo	1
145	49	efapi	1
146	49	palmital	1
147	49	passo	1
148	50	efapi	1
149	50	palmital	1
150	50	passo	1
151	51	efapi	1
152	51	palmital	1
153	51	passo	1
154	52	efapi	1
155	52	palmital	1
156	52	passo	1
157	53	efapi	1
158	53	palmital	1
159	53	passo	1
160	54	efapi	1
161	54	palmital	1
162	54	passo	1
163	55	efapi	1
164	55	palmital	1
165	55	passo	1
166	56	efapi	1
167	56	palmital	1
168	56	passo	1
169	57	efapi	1
170	57	palmital	1
171	57	passo	1
172	58	efapi	1
173	58	palmital	1
174	58	passo	1
175	59	efapi	1
176	59	palmital	1
177	59	passo	1
178	60	efapi	1
179	60	palmital	1
180	60	passo	1
181	61	efapi	1
182	61	palmital	1
183	61	passo	1
184	62	efapi	1
185	62	palmital	1
186	62	passo	1
187	63	efapi	1
188	63	palmital	1
189	63	passo	1
190	64	efapi	1
191	64	palmital	1
192	64	passo	1
193	65	efapi	1
194	65	palmital	1
195	65	passo	1
196	66	efapi	1
197	66	palmital	1
198	66	passo	1
199	67	efapi	1
200	67	palmital	1
201	67	passo	1
202	68	efapi	1
203	68	palmital	1
204	68	passo	1
205	69	efapi	1
206	69	palmital	1
207	69	passo	1
208	70	efapi	1
209	70	palmital	1
210	70	passo	1
211	71	efapi	1
212	71	palmital	1
213	71	passo	1
214	72	efapi	1
215	72	palmital	1
216	72	passo	1
217	73	efapi	1
218	73	palmital	1
219	73	passo	1
220	74	efapi	1
221	74	palmital	1
222	74	passo	1
223	75	efapi	1
224	75	palmital	1
225	75	passo	1
226	76	efapi	1
227	76	palmital	1
228	76	passo	1
229	77	efapi	1
230	77	palmital	1
231	77	passo	1
232	78	efapi	1
233	78	palmital	1
234	78	passo	1
235	79	efapi	1
236	79	palmital	1
237	79	passo	1
238	80	efapi	1
239	80	palmital	1
240	80	passo	1
241	81	efapi	1
242	81	palmital	1
243	81	passo	1
244	82	efapi	1
245	82	palmital	1
246	82	passo	1
247	83	efapi	1
248	83	palmital	1
249	83	passo	1
250	84	efapi	1
251	84	palmital	1
252	84	passo	1
253	85	efapi	1
254	85	palmital	1
255	85	passo	1
256	86	efapi	1
257	86	palmital	1
258	86	passo	1
259	87	efapi	1
260	87	palmital	1
261	87	passo	1
262	88	efapi	1
263	88	palmital	1
264	88	passo	1
265	89	efapi	1
266	89	palmital	1
267	89	passo	1
268	90	efapi	1
269	90	palmital	1
270	90	passo	1
271	91	efapi	1
272	91	palmital	1
273	91	passo	1
274	92	efapi	1
275	92	palmital	1
276	92	passo	1
277	93	efapi	1
278	93	palmital	1
279	93	passo	1
280	94	efapi	1
281	94	palmital	1
282	94	passo	1
283	95	efapi	1
284	95	palmital	1
285	95	passo	1
286	96	efapi	1
289	97	efapi	1
287	96	palmital	1
288	96	passo	1
290	97	palmital	1
292	98	efapi	1
293	98	palmital	1
294	98	passo	1
298	100	efapi	1
299	100	palmital	1
300	100	passo	1
291	97	passo	1
295	99	efapi	1
296	99	palmital	1
297	99	passo	1
301	101	efapi	1
302	101	palmital	1
303	101	passo	1
304	102	efapi	1
305	102	palmital	1
306	102	passo	1
307	103	efapi	1
308	103	palmital	1
309	103	passo	1
310	104	efapi	1
311	104	palmital	1
312	104	passo	1
313	105	efapi	1
314	105	palmital	1
315	105	passo	1
316	106	efapi	1
317	106	palmital	1
318	106	passo	1
319	107	efapi	1
320	107	palmital	1
321	107	passo	1
322	108	efapi	1
323	108	palmital	1
324	108	passo	1
325	109	efapi	1
326	109	palmital	1
327	109	passo	1
328	110	efapi	1
329	110	palmital	1
330	110	passo	1
331	111	efapi	1
332	111	palmital	1
333	111	passo	1
334	112	efapi	1
335	112	palmital	1
336	112	passo	1
337	113	efapi	1
338	113	palmital	1
340	114	efapi	1
341	114	palmital	1
342	114	passo	1
343	115	efapi	1
344	115	palmital	1
345	115	passo	1
346	116	efapi	1
347	116	palmital	1
348	116	passo	1
349	117	efapi	1
350	117	palmital	1
351	117	passo	1
352	118	efapi	1
353	118	palmital	1
354	118	passo	1
355	119	efapi	1
356	119	palmital	1
357	119	passo	1
358	120	efapi	1
359	120	palmital	1
360	120	passo	1
361	121	efapi	1
362	121	palmital	1
363	121	passo	1
364	122	efapi	1
365	122	palmital	1
366	122	passo	1
367	123	efapi	1
368	123	palmital	1
369	123	passo	1
370	124	efapi	1
371	124	palmital	1
372	124	passo	1
373	125	efapi	1
374	125	palmital	1
375	125	passo	1
376	126	efapi	1
377	126	palmital	1
378	126	passo	1
379	127	efapi	1
380	127	palmital	1
381	127	passo	1
382	128	efapi	1
383	128	palmital	1
384	128	passo	1
339	113	passo	0
\.


--
-- Data for Name: Subcategories; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."Subcategories" ("Id", "Name", "CategoryId") FROM stdin;
1	Frutas	3
2	Cremes	3
3	Diamond	3
4	Ituzinho	3
5	Kids	3
6	Grego	3
7	2L	4
8	1,5L	4
9	Best Cup	4
10	Grand Nevado	4
11	La Sobremesa	3
12	banana	6
13	guaraná	6
14	80 g	7
15	Abacaxi com coco	5
16	Iogurte grego com morango	5
17	450 g	12
18	Brigadeiro	9
19	Crocante	9
20	Coco	12
21	Chocolate	12
22	Napolicup	4
23	Super Barrita	3
24	Napolitano	3
25	Los Palitos Mexicanos	3
26	Grand Nevado	4
27	Copinho Gourmet	4
28	Bombom no Palito	3
29	Linha +	3
30	Cascão	8
31	Chocolate	8
32	Morango	8
33	Farofa Doce	8
34	Caramelo	8
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."Users" ("Id", "Username", "Email", "PasswordHash", "Role") FROM stdin;
1	admin	admin@eskimo.com	$2a$11$jbZF.ap3P3Yyy723w/GIxexei2qEJ4x6Za/T0.PVIiG.IHzXGr72e	admin
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: eskimo_user
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250730144303_InitFinal	9.0.4
\.


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 12, true);


--
-- Name: OrderItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."OrderItems_Id_seq"', 1, true);


--
-- Name: Orders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."Orders_Id_seq"', 1, true);


--
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 128, true);


--
-- Name: Settings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."Settings_Id_seq"', 1, true);


--
-- Name: StoreProductVisibilities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."StoreProductVisibilities_Id_seq"', 384, true);


--
-- Name: StoreStocks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."StoreStocks_Id_seq"', 384, true);


--
-- Name: Subcategories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."Subcategories_Id_seq"', 34, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: eskimo_user
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: OrderItems PK_OrderItems; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id");


--
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- Name: Products PK_Products; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- Name: Settings PK_Settings; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Settings"
    ADD CONSTRAINT "PK_Settings" PRIMARY KEY ("Id");


--
-- Name: StoreProductVisibilities PK_StoreProductVisibilities; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."StoreProductVisibilities"
    ADD CONSTRAINT "PK_StoreProductVisibilities" PRIMARY KEY ("Id");


--
-- Name: StoreStocks PK_StoreStocks; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."StoreStocks"
    ADD CONSTRAINT "PK_StoreStocks" PRIMARY KEY ("Id");


--
-- Name: Subcategories PK_Subcategories; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Subcategories"
    ADD CONSTRAINT "PK_Subcategories" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_OrderItems_OrderId; Type: INDEX; Schema: public; Owner: eskimo_user
--

CREATE INDEX "IX_OrderItems_OrderId" ON public."OrderItems" USING btree ("OrderId");


--
-- Name: IX_Products_CategoryId; Type: INDEX; Schema: public; Owner: eskimo_user
--

CREATE INDEX "IX_Products_CategoryId" ON public."Products" USING btree ("CategoryId");


--
-- Name: IX_Products_SubcategoryId; Type: INDEX; Schema: public; Owner: eskimo_user
--

CREATE INDEX "IX_Products_SubcategoryId" ON public."Products" USING btree ("SubcategoryId");


--
-- Name: IX_StoreProductVisibilities_ProductId; Type: INDEX; Schema: public; Owner: eskimo_user
--

CREATE INDEX "IX_StoreProductVisibilities_ProductId" ON public."StoreProductVisibilities" USING btree ("ProductId");


--
-- Name: IX_StoreStocks_ProductId; Type: INDEX; Schema: public; Owner: eskimo_user
--

CREATE INDEX "IX_StoreStocks_ProductId" ON public."StoreStocks" USING btree ("ProductId");


--
-- Name: IX_Subcategories_CategoryId; Type: INDEX; Schema: public; Owner: eskimo_user
--

CREATE INDEX "IX_Subcategories_CategoryId" ON public."Subcategories" USING btree ("CategoryId");


--
-- Name: OrderItems FK_OrderItems_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- Name: Products FK_Products_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id");


--
-- Name: Products FK_Products_Subcategories_SubcategoryId; Type: FK CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Products"
    ADD CONSTRAINT "FK_Products_Subcategories_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES public."Subcategories"("Id");


--
-- Name: StoreProductVisibilities FK_StoreProductVisibilities_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."StoreProductVisibilities"
    ADD CONSTRAINT "FK_StoreProductVisibilities_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- Name: StoreStocks FK_StoreStocks_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."StoreStocks"
    ADD CONSTRAINT "FK_StoreStocks_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Products"("Id") ON DELETE CASCADE;


--
-- Name: Subcategories FK_Subcategories_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: eskimo_user
--

ALTER TABLE ONLY public."Subcategories"
    ADD CONSTRAINT "FK_Subcategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO eskimo_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO eskimo_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO eskimo_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO eskimo_user;


--
-- PostgreSQL database dump complete
--

