services:
  - type: web
    name: backend-eskimo
    env: dotnet
    plan: free
    branch: main
    rootDir: .
    buildCommand: dotnet restore
    startCommand: dotnet run --project e-commerce.csproj
